# Numpy (넘파이)
### 1. Numpy 란?


Numpy는 "Numerical Python"의 줄임말로, Python에서 과학 계산을 위한 핵심 라이브러리입니다. Numpy는 파이썬의 기본 데이터 구조를 확장하여, 다차원 배열을 효과적으로 처리할 수 있는 기능을 제공합니다.
<br />

Numpy의 가장 큰 특징은 다차원 배열 객체인 ndarray를 제공한다는 점입니다. 이 배열은 동일한 유형의 원소들로 구성되며, 파이썬의 리스트에 비해 빠른 연산과 더 적은 메모리를 사용합니다.

<img src="./sorce/Numpy.png" height="200" width="500">


### 2. Numpy 장점
* 효율적인 메모리 사용


Numpy 배열은 동일한 데이터 타입을 가진 원소들로 이루어져 있어, 메모리를 효율적으로 활용합니다. 그 결과, 대용량 데이터를 다룰 때에도 높은 성능을 보장합니다.



* 빠른 연산 속도


Numpy는 내부적으로 C언어로 구현되어 있어 연산이 매우 빠릅니다. 복잡한 수학적 연산도 빠르게 처리할 수 있습니다.



* 편리한 수치 연산 기능


Numpy는 수학적 연산을 간편하게 수행할 수 있는 다양한 함수를 제공합니다. 이에는 기본적인 산술 연산부터 복잡한 선형대수 연산까지 포함됩니다.


<br />


Numpy는 데이터 분석, 머신러닝, 이미지 처리, 컴퓨터 그래픽스 등 다양한 분야에서 사용됩니다. 특히 파이썬의 대표적인 데이터 분석 라이브러리인 pandas와 시각화 라이브러리인 matplotlib, 그리고 머신러닝 라이브러리인 scikit-learn, TensorFlow, PyTorch 등은 모두 내부적으로 Numpy를 활용합니다. 따라서 Numpy는 파이썬을 활용한 과학 계산과 데이터 분석의 기본적인 라이브러리라고 할 수 있습니다.

---
numpy를 사용하기 위해서는 import 해야합니다. 아래와 같이 임포트 하면됩니다. 여기서 as는 코드의 가독성을 높이고, 라이브러리의 이름을 짧게 사용하기 위해 사용됩니다. numpy는 보통 np로 짧게 사용합니다.

In [1]:
%pip install numpy

import numpy as np

Note: you may need to restart the kernel to use updated packages.


<br />
<br />

---
## [Numpy 배열 만들기]
* NumPy에서 가장 중요한 데이터 구조는 ndarray (N-dimensional array, 다차원 배열)
* 이 배열은 Python의 기본 리스트보다 연산 속도가 빠르고, 메모리 사용량이 적음


#### (1) numpy.array() : 리스트를 Numpy 배열로 변환
<br />
numpy.array는 입력 데이터(리스트, 리스트의 튜플, 다른 배열 등)를 ndarray로 변환합니다.

In [2]:
# 여기에 코드를 작성해 보세요!
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# 모범답안은 아래와 같습니다.

import numpy as np

# 리스트를 NumPy 배열로 변환
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))  # <class 'numpy.ndarray'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


### (2) numpy.zeros()

numpy.zeros는 모든 원소가 0인 배열을 생성합니다. 괄호 안의 숫자는 배열의 형태를 나타냅니다.


이 함수는 **배열을 초기화할 때 매우 자주 사용**됩니다.  
예를 들어 머신러닝에서 가중치 배열을 0으로 초기화하거나,  
데이터를 담기 전에 빈 그릇처럼 배열을 미리 만들어두는 데 사용됩니다.

In [4]:
# 여기에 코드를 작성해 보세요!
zero_array = np.zeros((100, 100))
print(zero_array)
zero_array.dtype 

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


dtype('float64')

In [5]:
# 모범답안은 아래와 같습니다.
zero_arr = np.zeros((3, 4))  # 3행 4열 배열
print(zero_arr)
zero_arr.dtype

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


dtype('float64')

### (3) numpy.ones()

numpy.ones는 모든 원소가 1인 배열을 생성합니다. (2, 3)은 이 배열이 2행 3열의 2차원 배열임을 의미합니다. 이 함수는 가중치를 초기화 할 때, 연산에서 모든 원소가 1인 배열이 필요할 때 주로 사용됩니다.

In [6]:
# 여기에 코드를 작성해 보세요!
one_array = np.ones((5, 5))
print(one_array)
one_array.dtype

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


dtype('float64')

In [7]:
# 모범답안은 아래와 같습니다.
one_arr = np.ones((2, 3))  # 2행 3열 배열
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


### (4) numpy.arange()
<br />
numpy.arange는 특정 구간 안에서 일정 간격의 값으로 구성된 배열을 생성합니다.
   start 값에서 시작하여 stop 값까지 step 간격으로 숫자를 생성합니다.  
   여기서 stop값은 범위에 포함되지 않습니다.
<br />


<img src="./sorce/arange.png" height="200" width="600">




`numpy.arange()`는 파이썬의 `range()` 함수처럼  
**규칙적인 간격의 숫자 배열**을 만들 때 사용합니다.  
하지만 리스트가 아닌 **NumPy 배열(ndarray)**로 만들어주기 때문에  
연산이 빠르고 다양한 배열 연산에 바로 사용할 수 있습니다.

이 함수는 **데이터 인덱스, 샘플 시점, 수열 기반 초기값 생성 등**  
다양한 실습에서 반복적으로 사용됩니다.


In [8]:
# 여기에 코드를 작성해 보세요!
for i in range(1, 10, 2):
    print(i)

1
3
5
7
9


In [9]:
# 모범답안은 아래와 같습니다.
for i in range(1, 10, 2):
  print(i)

1
3
5
7
9


In [10]:
# 여기에 코드를 작성해 보세요!
range_array = np.arange(1, 10, 2)
print(range_array)

[1 3 5 7 9]


In [11]:
# 모범답안은 아래와 같습니다.
range_arr = np.arange(1, 10, 2)  # 1부터 10까지 2씩 증가하는 배열
print(range_arr)

[1 3 5 7 9]


### (5)numpy.linspace()
numpy.linspace는 지정된 범위에서 균일한 간격으로 숫자 생성합니다.

`numpy.linspace()`는 시작값과 끝값을 기준으로  
**원하는 개수만큼 균등한 간격의 값을 생성**할 때 사용합니다.

`arange()`는 간격(step)을 기준으로 숫자를 생성하지만,  
`linspace()`는 **“개수”를 기준으로 균등 분할**합니다.  
→ 주로 **시각화 축 값 생성, 함수 그래프 그리기, 시뮬레이션 시간 설정** 등에 자주 사용됩니다.


In [12]:
# 여기에 코드를 작성해 보세요!
linspace_array = np.linspace(0, 10, 5)
print(linspace_array)

[ 0.   2.5  5.   7.5 10. ]


In [13]:
# 모범답안은 아래와 같습니다.
linspace_arr = np.linspace(0, 100, 5)  # 0부터 100까지 5개의 숫자를 균등 간격으로 생성
print(linspace_arr)

[  0.  25.  50.  75. 100.]


### (6)numpy.random()
numpy.random는 난수 배열을 생생성합니다.

`numpy.random`은 난수(무작위 수)를 생성할 수 있는 도구 모음입니다.  
머신러닝, 통계 분석, 시뮬레이션 등 다양한 분야에서  
**샘플 데이터를 만들거나, 확률 기반 처리를 할 때 필수적으로 사용됩니다.**

예를 들어,
- 무작위로 정수를 뽑거나 (`randint`)
- 0~1 사이의 실수 배열을 만들거나 (`rand`, `random`)
- 정규분포를 따르는 난수를 만들거나 (`normal`)
등 다양한 난수 생성이 가능합니다.

In [14]:
# 여기에 코드를 작성해 보세요!
random_array = np.random.rand(4, 4)
print(random_array)

[[0.91958989 0.98918815 0.17709814 0.05451729]
 [0.6317014  0.26675314 0.39368024 0.00344204]
 [0.74778168 0.5333401  0.17991446 0.43999785]
 [0.44840075 0.55511376 0.19757982 0.4183088 ]]


<br />
<br />

---
## [Numpy 배열 주요연산]
Numpy는 배열에 대한 기본적인 수학 연산을 지원합니다. 이 연산은 배열의 각 요소에 개별적으로 적용되며, 새 배열을 생성하여 결과를 반환합니다.

#### (1) 기본연산(덧셈,뺄셈,곱셈,나눗셈)
리스트와 달리 NumPy 배열은 요소별 연산 가능


<img src="./sorce/numpyarray.png" height="250" width="400">


In [15]:
# 여기에 코드를 작성해 보세요!
array1 = np.array([10,20,30])
array2 = np.array([1,2,3])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [16]:
# 모범답안은 아래와 같습니다.
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

print(arr1 + arr2)  # [11 22 33]  ** + 는 덧셈
print(arr1 - arr2)  # [ 9 18 27]  ** - 는 뺄셈
print(arr1 * arr2)  # [10 40 90]  ** * 는 곱셈
print(arr1 / arr2)  # [10. 10. 10.] ** / 는 나눗셈


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


#### (2) 배열의 형태(shape)와 크기(size) 확인
배열의 행과 열 개수를 shape, 원소 개수를 size로 확인 가능

In [17]:
# 여기에 코드를 작성해 보세요!
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)
print(array.size)

(2, 3)
6


In [18]:
# 모범답안은 아래와 같습니다.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3) → 2행 3열
print(arr.size)   # 6 → 총 원소 개수

(2, 3)
6


#### (3) 배열 인덱싱 & 슬라이싱
Python 리스트처럼 인덱싱과 슬라이싱 가능

In [19]:
# 여기에 코드를 작성해 보세요!
array = np.array([12, 65, 8, 9, 35, 82, 17])
print(array[3])
print(array[4:])
print(array[4:7])
print(array[-3:])

9
[35 82 17]
[35 82 17]
[35 82 17]


In [20]:
# 모범답안은 아래와 같습니다.
arr = np.array([10, 20, 30, 40, 50])

print(arr[2])   # 30 (인덱싱)
print(arr[1:4]) # [20 30 40] (슬라이싱

30
[20 30 40]


<br />

___
## [Numpy 배열의 주요 연산 (Numpy 집계 함수)]


Numpy는 데이터 분석을 위해 다양한 집계 함수(Aggregate functions)를 제공합니다. 이러한 함수를 사용하면 배열의 요소에 대해 특정 계산을 수행할 수 있습니다. 대표적인 집계 함수들은 다음과 같습니다.



* np.sum(): 배열의 모든 요소의 합을 계산합니다.
* np.min(), np.max(): 배열의 최소값 또는 최대값을 찾습니다.
* np.mean(): 배열의 평균 값을 계산합니다.
* np.median(): 배열의 중간값(median)을 찾습니다.
* np.std(): 배열의 표준 편차를 계산합니다.
* np.var(): 배열의 분산을 계산합니다.


### (1) np.mean()

In [21]:
# 여기에 코드를 작성해 보세요!0
array = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(np.mean(array))

5.5


In [22]:
# 모범답안은 아래와 같습니다.
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # 3.0

3.0


### (2) np.sum()


<img src="./sorce/npmean.png" height="400" width="600">

In [23]:
# 여기에 코드를 작성해 보세요!
print(np.sum(array))
print(np.sum(array, axis=0))
print(np.sum(array, axis=1))


55
[ 7  9 11 13 15]
[15 40]


In [24]:
# 모범답안은 아래와 같습니다.
print(np.sum(arr))  # 15

15


### (3) np.min(), np.max()

In [25]:
# 여기에 코드를 작성해 보세요!
print(np.max(array))
print(np.min(array))

print(np.max(array, axis=0))
print(np.max(array, axis=1))
print(np.min(array, axis=0))
print(np.min(array, axis=1))

10
1
[ 6  7  8  9 10]
[ 5 10]
[1 2 3 4 5]
[1 6]


In [26]:
# 모범답안은 아래와 같습니다.
print(np.max(arr))  # 5
print(np.min(arr))  # 1


5
1


### (4)reshape()
배열의 형태를 원하는 크기로 변환 가능


In [27]:
# 여기에 코드를 작성해 보세요!
array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = array.reshape(2,3)
print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [28]:
# 모범답안은 아래와 같습니다.
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  # 2행 3열로 변경
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


___

## [참고] 추가학습자료(numpy)


## Numpy 인덱싱


Numpy 배열 인덱싱(indexing)은 리스트 인덱싱과 매우 유사하게 작동합니다. 인덱싱(Indexing)은 특정 위치의 데이터에 접근하는 것을 의미합니다. 인덱싱을 이용해 특정 위치에 있는 값을 가져오거나 설정할 수 있습니다.

In [29]:
# 여기에 코드를 작성해 보세요!
array = np.array([1, 2, 3, 4, 5])
print(f"Origianl array: {array}")
print(f"First element: {array[0]}")
print(f"Last element: {array[-1]}")

array[0] = 10
print(f"Array after modification: {array}")

Origianl array: [1 2 3 4 5]
First element: 1
Last element: 5
Array after modification: [10  2  3  4  5]


In [30]:
# 모범답안은 아래와 같습니다.
arr = np.array([1, 2, 3, 4, 5])
print("Original array: ", arr)
print("First element: ", arr[0])  # 첫 번째 원소
print("Last element: ", arr[-1])  # 마지막 원소

arr[0] = 10  # 첫 번째 원소 값을 변경
print("Array after modification: ", arr)

Original array:  [1 2 3 4 5]
First element:  1
Last element:  5
Array after modification:  [10  2  3  4  5]


In [31]:
a = [[1,2,3,4], [5,6,7,8]]
a[1][2]  # 리스트의 인덱싱

7

### 슬라이싱


슬라이싱은 배열의 일부분을 선택하는 방법을 의미합니다. 넘파이 배열에서 슬라이싱을 수행하면 원본 데이터를 변경하게 될 수 있으므로 주의 해야합니다.

In [32]:
# 여기에 코드를 작성해 보세요!
array = np.array([1, 2, 3, 4, 5])
print(f"Original array: {array}")

slice_array = array[1:4]
print(f"Sliced array: {slice_array}")

slice_array[0] = 10
print(f"Modified sliced array: {slice_array}")
print(f"Original array after modification: {array}")

Original array: [1 2 3 4 5]
Sliced array: [2 3 4]
Modified sliced array: [10  3  4]
Original array after modification: [ 1 10  3  4  5]


In [33]:
# 모범답안은 아래와 같습니다.
arr = np.array([1, 2, 3, 4, 5])
print("Original array: ", arr)

slice_arr = arr[1:4]  # 인덱스 1에서 3까지의 슬라이스
print("Slice of the array: ", slice_arr)

slice_arr[0] = 10  # 슬라이스의 첫 번째 원소 값을 변경
print("Slice after modification: ", slice_arr)
print("Original array after modification: ", arr)  # 원래 배열도 변경됨

Original array:  [1 2 3 4 5]
Slice of the array:  [2 3 4]
Slice after modification:  [10  3  4]
Original array after modification:  [ 1 10  3  4  5]


___

# [np.random 부록]  난수 생성


난수 생성은 컴퓨터 프로그래밍에서 자주 사용되는 기능 중 하나입니다. 통계적 분석, 머신러닝, 시뮬레이션, 암호화 등 다양한 분야에서 사용됩니다.



* np.random.rand() : 0과 1 사이에서 균일 분포를 따르는 난수를 생성합니다. 함수에 전달된 인수의 개수에 따라 다차원 배열을 생성하는 데 사용할 수 있습니다. 예를 들어, np.random.rand(5,3)을 호출하면 5x3 크기의 배열이 생성되며, 각 요소는 0과 1 사이의 랜덤한 숫자입니다.
* np.random.randn() : 표준 정규 분포(평균이 0이고 표준편차가 1인 분포)를 따르는 난수를 생성합니다.
* np.random.randint() : 특정 범위 내에서 랜덤한 정수를 생성합니다. 두 개의 인수를 받으며, 첫 번째 인수는 범위의 시작(포함)이고 두 번째 인수는 범위의 끝(비포함)입니다.
* np.random.random() : 0과 1 사이에서 균일 분포를 따르는 난수를 생성합니다. 인수로 튜플을 받아 다차원 배열을 생성할 수 있습니다.

In [34]:
# 여기에 코드를 작성해 보세요!
print(np.random.rand())
print(np.random.randn())
print(np.random.randint(1, 10))
print(np.random.random())

0.07272903807911912
-1.1187494373838514
5
0.38136791567986816


In [35]:
# 모범답안은 아래와 같습니다.
# rand: 0과 1 사이의 균일 분포에서 난수 생성
print("Random number between 0 and 1: ", np.random.rand())

# randn: 표준 정규 분포에서 난수 생성
print("Random number from standard normal distribution: ", np.random.randn())

# randint: 주어진 범위에서 임의의 정수 생성
print("Random integer between 1 and 10: ", np.random.randint(1, 10))

# random: 0과 1 사이의 균일 분포에서 난수 생성 (rand와 비슷하지만 다른 형태의 인자를 받음)
print("Random number between 0 and 1: ", np.random.random())


Random number between 0 and 1:  0.9124927565559362
Random number from standard normal distribution:  -0.5411184688900358
Random integer between 1 and 10:  5
Random number between 0 and 1:  0.4384481639330089


___

# [참고] Numpy 유용한 함수
### (1)  np.any(), np.all()

np.any() 함수는 배열 내에서 어느 한 요소라도 참(True)이면 True를 반환하고, np.all() 함수는 배열의 모든 요소가 참(True)일 때 True를 반환합니다.

In [36]:
# 여기에 코드를 작성해 보세요!
array = np.array([True, True, False])
print(np.any(array))
print(np.all(array))

True
False


In [37]:
# 모범답안은 아래와 같습니다.
arr = np.array([True, False, True])

print("Any: ", np.any(arr)) # or
print("All: ", np.all(arr)) # and

Any:  True
All:  False


### (2) np.where()


np.where() 함수는 특정 조건을 만족하는 요소의 인덱스를 반환합니다.

In [38]:
# 여기에 코드를 작성해 보세요!
array = np.array([2, 1, 4, 3, 5])
index = np.where(arr > 3)

print(f"Index : {index}")
print(f"Value : {arr[index]}")

Index : (array([], dtype=int64),)
Value : []


In [39]:
# 모범답안은 아래와 같습니다.
arr = np.array([1, 2, 3, 4, 5])
index = np.where(arr > 3)

print("Index: ", index)  # 3, 4
print("Values: ", arr[index])

Index:  (array([3, 4]),)
Values:  [4 5]
