
# 🧹 데이터 전처리 실습

이 파일에서는 머신러닝을 위한 데이터를 준비하는 전처리 과정을 scikit-learn 으로 실습해봅니다.



## ① 데이터 불러오기

데이터 분석의 첫 걸음은 데이터를 불러오는 것입니다.  
보통 CSV 파일이나 엑셀 파일 등 다양한 포맷의 데이터를 사용합니다.



## ② 범주형 변수 인코딩

머신러닝 알고리즘은 숫자 데이터를 입력으로 받기 때문에,  
범주형(문자형) 변수는 숫자로 변환해주어야 합니다.  
Label Encoding 또는 One-Hot Encoding을 주로 사용합니다.



## ③ 수치형 변수 정규화 (스케일링)

특성(feature)마다 단위나 범위가 다를 수 있기 때문에, 이를 맞춰주는 과정이 필요합니다.  
MinMaxScaler, StandardScaler 등을 사용해 정규화합니다.





---

<br/><br/>

### 데이터 인코딩

### 레이블 인코딩(Label encoding)

- 각 범주마다 인덱스를 붙여 수치화하는 방법
- sklearn.preprocessing  모듈을 사용합니다.
- 인코딩을 할 때에는 fit - transform 메서드를 활용합니다.

In [1]:
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']


In [2]:
# 필요한 라이브러리를 import 하세요
# LabelEncoder를 객체로 생성한 후 , fit( ) 과 transform( ) 으로 label 인코딩 수행.

# 여기에 코드를 작성하세요!
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

encoder.fit(items)
result = encoder.transform(items)

print(f"result: {result}")


result: [0 1 4 5 3 3 2 2]


In [3]:
## 모범 답안

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:',labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [4]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [5]:
print('디코딩 원본 값:',encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

디코딩 원본 값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


### 원-핫 인코딩(One-Hot encoding) - sklean.preprocessing.OneHotEncoder

- 범주형 데이터를 머신러닝 모델이 이해할 수 있도록 숫자 벡터로 변환하는 방법
- 각 범주를 0과 1로 구성된 벡터로 표현하며, 해당 범주에만 1을 주고 나머지는 모두 0으로 표시합니다.
(1 : True / 0: False)
- scikit-learn 에서 원핫인코딩을 적용하기 위해서는 우선 LabelEncoding 을 수행해야 합니다.

In [6]:
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']


In [7]:
# 필요한 라이브러리를 import 하세요
# scikit-learn 에서 원핫인코딩을 적용하기 위해서는 우선 LabelEncoding 을 수행해야 합니다.


# 여기에 코드를 작성하세요
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(items)
result_le = encoder.transform(items)

print(result_le)
result_le = result_le.reshape(-1,1) # -1: 자동으로 크기조절 / 차원의 크기 : 1로 고정
print(result_le)

encoder_oh = OneHotEncoder()
encoder_oh.fit(result_le)

result_oh = encoder_oh.transform(result_le)

print(result_oh.toarray())

[0 1 4 5 3 3 2 2]
[[0]
 [1]
 [4]
 [5]
 [3]
 [3]
 [2]
 [2]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [8]:
## 모범 답안


from sklearn.preprocessing import OneHotEncoder
import numpy as np


# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환합니다.
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
# 2차원 데이터로 변환합니다.
labels = labels.reshape(-1,1)

# 원-핫 인코딩을 적용합니다.
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


### 원-핫 인코딩 - pd.get_dummies()
- scikit-learn 의 원핫인코딩은 사용법이 불편하기 떄문에 대부분 원핫인코딩은 pandas 를 활용합니다.
- pd.get_dummies()를 활용하면, 데이터프레임형태의 인코딩된 결과를 얻을 수 있습니다.

In [9]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'item':['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서'] })
display(df)

item
0    TV
1   냉장고
2  전자렌지
3   컴퓨터
4   선풍기
5   선풍기
6    믹서
7    믹서

In [10]:
# 여기에 코드를 작성하세요!
pd.get_dummies(df)


item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0     True     False    False     False      False     False
1    False      True    False     False      False     False
2    False     False    False     False       True     False
3    False     False    False     False      False      True
4    False     False    False      True      False     False
5    False     False    False      True      False     False
6    False     False     True     False      False     False
7    False     False     True     False      False     False

In [11]:
## 모범 답안

pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0     True     False    False     False      False     False
1    False      True    False     False      False     False
2    False     False    False     False       True     False
3    False     False    False     False      False      True
4    False     False    False      True      False     False
5    False     False    False      True      False     False
6    False     False     True     False      False     False
7    False     False     True     False      False     False

만약 데이터에 결측치가 있다면 어떻게 될까요?

In [12]:
# get_dummies 의 결측치 처리를 위한 파라미터 소개
season = pd.DataFrame(['spring', 'summer', 'fall', np.nan])
season

0
0  spring
1  summer
2    fall
3     NaN

In [13]:
# 여기에 코드를 작성하세요!
display( pd.get_dummies(season) )

display( pd.get_dummies(season, dummy_na=True) )

0_fall  0_spring  0_summer
0   False      True     False
1   False     False      True
2    True     False     False
3   False     False     False

0_fall  0_spring  0_summer  0_nan
0   False      True     False  False
1   False     False      True  False
2    True     False     False  False
3   False     False     False   True

In [14]:
## 모범 답안


pd.get_dummies(season)

0_fall  0_spring  0_summer
0   False      True     False
1   False     False      True
2    True     False     False
3   False     False     False

In [15]:
## 모범 답안


pd.get_dummies(season, dummy_na=True)

0_fall  0_spring  0_summer  0_nan
0   False      True     False  False
1   False     False      True  False
2    True     False     False  False
3   False     False     False   True



---



###  피처 스케일링과 정규화

### StandardScaler


- StandardScaler는 데이터의 평균을 0, 표준편차를 1로 변환하여 정규 분포 형태로 표준화합니다.
- 스케일이 다른 특성들을 동일한 기준으로 맞춰주기 위해 사용합니다.
- 학습 데이터에 fit_transform()을 적용하고, 테스트 데이터에는 transform()만 적용해야 합니다.
이렇게 해야 테스트 데이터의 정보가 학습에 반영되지 않아 데이터 누수를 방지할 수 있습니다.

In [16]:
from sklearn.datasets import load_iris
import pandas as pd

# 붓꽃 데이터 셋을 로딩하고 DataFrame으로 변환합니다.
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())


feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [17]:
# 여기에 코드를 작성하세요!
from sklearn.preprocessing import StandardScaler

# StandardScaler객체 생성
scaler = StandardScaler()

#  StandardScaler 로 데이터 셋 변환. fit( ) 과 transform( ) 호출.
scaler.fit(iris_df) # 데이터 프레임 형태로 넣어도 정상작동!
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

display(iris_df_scaled)

print('표준정규화 이후 평균')   # 효율을 위해 0에 근사
print(iris_df_scaled.mean())

print('표준정규화 이후 분산')   # 1에 근사
print(iris_df_scaled.var())



sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

표준정규화 이후 평균
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
표준정규화 이후 분산
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [18]:
## 모범답안

from sklearn.preprocessing import StandardScaler

# StandardScaler객체 생성
scaler = StandardScaler()
# StandardScaler 로 데이터 셋 변환. fit( ) 과 transform( ) 호출.
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

#transform( )시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


### MinMaxScaler

- MinMaxScaler는 데이터를 0과 1 사이의 범위로 압축하는 정규화 방식입니다.
- 특성 간의 최소값과 최대값을 기준으로 스케일을 조정하므로, 모든 특성이 동일한 범위를 가지게 됩니다.
- fit_transform()은 반드시 학습 데이터에만 적용하고, 테스트 데이터는 transform()만 해야 합니다.


In [21]:
# 여기에 코드를 작성하세요!
from sklearn.preprocessing import MinMaxScaler
# MinMaxScaler객체 생성
scaler = MinMaxScaler()
# MinMaxScaler 로 데이터 셋 변환. fit() 과 transform() 호출.
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df) # numpy 객체

iris_df_scaled = pd.DataFrame(iris_scaled, columns=iris.feature_names)
display(iris_df_scaled)
print(f"스케일링 후 최소값\n{iris_df_scaled.min()}")
print(f"스케일링 후 최대값\n{iris_df_scaled.max()}")

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.222222          0.625000           0.067797          0.041667
1             0.166667          0.416667           0.067797          0.041667
2             0.111111          0.500000           0.050847          0.041667
3             0.083333          0.458333           0.084746          0.041667
4             0.194444          0.666667           0.067797          0.041667
..                 ...               ...                ...               ...
145           0.666667          0.416667           0.711864          0.916667
146           0.555556          0.208333           0.677966          0.750000
147           0.611111          0.416667           0.711864          0.791667
148           0.527778          0.583333           0.745763          0.916667
149           0.444444          0.416667           0.694915          0.708333

[150 rows x 4 columns]

스케일링 후 최소값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
스케일링 후 최대값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [20]:
## 모범답안

from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler객체 생성
scaler = MinMaxScaler()
# MinMaxScaler 로 데이터 셋 변환. fit() 과 transform() 호출.
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform()시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 최소 값')
print(iris_df_scaled.min())
print('\nfeature들의 최대 값')
print(iris_df_scaled.max())


feature들의 최소 값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최대 값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


### [참고] Scaler를 이용하여 학습 데이터와 테스트 데이터에 fit(), transform(), fit_transform() 적용 시 유의사항.

In [25]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 학습 데이터는 0 부터 10까지, 테스트 데이터는 0 부터 5까지 값을 가지는 데이터 세트로 생성
# Scaler클래스의 fit(), transform()은 2차원 이상 데이터만 가능하므로 reshape(-1, 1)로 차원 변경
train_array = np.arange(0, 11).reshape(-1, 1)
test_array =  np.arange(0, 6).reshape(-1, 1)

print(train_array)
print(test_array)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


*  최소값 0, 최대값 1로 변환하는 MinMaxScaler 객체 생성
* fit, transform 을 사용하여 데이터 변환

In [26]:
scaler = MinMaxScaler()
# fit()하게 되면 train_array 데이터의 최소값이 0, 최대값이 10으로 설정.
scaler.fit(train_array)
# 1/10 scale로 train_array 데이터 변환함. 원본 10-> 1로 변환됨.
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터:', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array 데이터:', np.round(train_scaled.reshape(-1), 2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


*  [확인!] 앞에서 생성한 MinMaxScaler에 test_array를 fit()하게 되면 원본 데이터의 최소값이 0, 최대값이 5으로 설정됨

* 실제 학습 데이터와 테스트 데이터의 변환 결과가 다른 것을 확인해보자.

In [27]:
scaler.fit(test_array)
# 1/5 scale로 test_array 데이터 변환함. 원본 5->1로 변환.
test_scaled = scaler.transform(test_array)
# train_array 변환 출력
print('원본 test_array 데이터:', np.round(test_array.reshape(-1), 2))
print('Scale된 test_array 데이터:', np.round(test_scaled.reshape(-1), 2))

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.2 0.4 0.6 0.8 1. ]


* 위와 같은 일이 벌어지지 않게 하려면?
-> train 데이터에 적용한 기준을 test에도 똑같이 적용해야한다.
-> train 데이터에 적용한 기준은 .fit() 메서드로 이루어진다.
-> 따라서 test에서는 . fit()을 하지 않는다!
-> test에서는 오직 변환만 수행한다 : .transform()


In [28]:
# 여기에 코드를 작성하세요!
from sklearn.preprocessing import MinMaxScaler
import numpy as np
# MinMaxScaler 객체 생성하세요
scaler = MinMaxScaler()

# 학습데이터에 인코딩하세요
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

test_scaled = scaler.transform(test_array)

# 테스트 데이터에 인코딩하세요


In [29]:
## 모범답안

scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print('원본 train_array 데이터:', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array 데이터:', np.round(train_scaled.reshape(-1), 2))

# test_array에 Scale 변환을 할 때는 반드시 fit()을 호출하지 않고 transform() 만으로 변환해야 함.
test_scaled = scaler.transform(test_array)
print('\n원본 test_array 데이터:', np.round(test_array.reshape(-1), 2))
print('Scale된 test_array 데이터:', np.round(test_scaled.reshape(-1), 2))


원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]
