# 🚀 머신러닝 실습 : 고객 구매 데이터로 성별 예측하기 (분류 문제)

> 인용구 추가



* 주어진 데이터는 백화점 고객의 1년 간 구매 데이터입니다.
* 고객 3,500명에 대한 학습용 데이터(y.csv, X.csv)를 이용하여 성별예측 모형을 만들어보세요.
* 모델의 성능은 자유롭게 측정해봅니다!

## [실습 프로세스]
1. 데이터 불러오기  
2. 데이터 탐색
3. 데이터 전처리  
4. 학습/테스트 데이터 분리  
5. 모델 선택 및 학습  
6. 예측 및 평가  



---



<br/><br/>

##   0. 구글 드라이브 마운트 하기

- 공유한 데이터를 불러오기 위해 구글 드라이브 마운트합니다.
- 마운트 후 경로는 , data 폴더에 접근할 수 있는 경로로 설정합니다.


In [ ]:
# 여기에 코드를 작성하세요

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [1]:
# %cd

%cd ./

c:\Users\User\GitHub\AIVLE\머신러닝



<br/>

---

<br/>
<br/>

# 0. 라이브러리 불러오기

* 라이브러리를 가져와서 과정을 준비합니다


필요한 라이브러리를 불러옵니다. (예: pandas, sklearn 등)

In [2]:
# 라이브러리 불러오기
# 여기에 코드를 작성하세요

import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings(action='ignore')

In [ ]:
## 모범답안

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings(action='ignore')

<br/>

---

<br/>
<br/>

# 1. 데이터 불러오기
* 데이터를 가져와서 과정을 준비합시다.
- 인코딩 방식은 'euc-kr' 을 활용하세요.
- 데이터 출처 : 한국데이터산업진흥원 빅데이터분석기사 실기 공개 예시 문항

- 독립 변수 데이터셋 : ./data/X.csv
- 종속 변수 데이터셋 : ./data/y.csv


데이터 파일을 불러옵니다. 보통 CSV 파일을 pandas로 읽어옵니다.

In [3]:
# 여기에 코드를 작성하세요

x = pd.read_csv('./data/X.csv', encoding = 'euc-kr')
y = pd.read_csv('./data/y.csv', encoding = 'euc-kr')

print(x.shape)
print(y.shape)

(3500, 10)
(3500, 2)


In [ ]:
## 모범답안

x = pd.read_csv('./data/X.csv', encoding='euc-kr')
y = pd.read_csv('./data/y.csv', encoding='euc-kr')

<br/>

---

<br/>
<br/>

# 2. 데이터 탐색하기
* 데이터를 이해할 수 있도록 탐색과정을 수행해봅시다.


데이터의 상위 몇 개 행을 출력하여 전체 구조를 미리 확인합니다.

In [4]:
# 여기에 코드를 작성하세요

x.head()

cust_id      총구매액     최대구매액       환불금액   주구매상품 주구매지점  내점일수   내점당구매건수  \
0        0  68282840  11264000  6860000.0      기타   강남점    19  3.894737   
1        1   2136000   2136000   300000.0     스포츠   잠실점     2  1.500000   
2        2   3197000   1639000        NaN  남성 캐주얼   관악점     2  2.000000   
3        3  16077620   4935000        NaN      기타   광주점    18  2.444444   
4        4  29050000  24000000        NaN      보석  본  점     2  1.500000   

     주말방문비율  구매주기  
0  0.527027    17  
1  0.000000     1  
2  0.000000     1  
3  0.318182    16  
4  0.000000    85

In [ ]:
## 모범답안

x.head()

In [5]:
# 여기에 코드를 작성하세요
y.head()

cust_id  gender
0        0       0
1        1       0
2        2       1
3        3       1
4        4       0

In [ ]:
## 모범답안

y.head()


데이터의 요약 정보나 통계 정보를 출력해 변수들의 유형과 분포를 확인합니다.

In [6]:
# 여기에 코드를 작성하세요
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   cust_id  3500 non-null   int64  
 1   총구매액     3500 non-null   int64  
 2   최대구매액    3500 non-null   int64  
 3   환불금액     1205 non-null   float64
 4   주구매상품    3500 non-null   object 
 5   주구매지점    3500 non-null   object 
 6   내점일수     3500 non-null   int64  
 7   내점당구매건수  3500 non-null   float64
 8   주말방문비율   3500 non-null   float64
 9   구매주기     3500 non-null   int64  
dtypes: float64(3), int64(5), object(2)
memory usage: 273.6+ KB


In [ ]:
## 모범답안

x.info()


데이터의 요약 정보나 통계 정보를 출력해 변수들의 유형과 분포를 확인합니다.

In [7]:
# 기술통계 확인
# 여기에 코드를 작성하세요
x.describe()

cust_id          총구매액         최대구매액          환불금액         내점일수  \
count  3500.000000  3.500000e+03  3.500000e+03  1.205000e+03  3500.000000   
mean   1749.500000  9.191925e+07  1.966424e+07  2.407822e+07    19.253714   
std    1010.507298  1.635065e+08  3.199235e+07  4.746453e+07    27.174942   
min       0.000000 -5.242152e+07 -2.992000e+06  5.600000e+03     1.000000   
25%     874.750000  4.747050e+06  2.875000e+06  2.259000e+06     2.000000   
50%    1749.500000  2.822270e+07  9.837000e+06  7.392000e+06     8.000000   
75%    2624.250000  1.065079e+08  2.296250e+07  2.412000e+07    25.000000   
max    3499.000000  2.323180e+09  7.066290e+08  5.637530e+08   285.000000   

           내점당구매건수       주말방문비율         구매주기  
count  3500.000000  3500.000000  3500.000000  
mean      2.834963     0.307246    20.958286  
std       1.912368     0.289752    24.748682  
min       1.000000     0.000000     0.000000  
25%       1.666667     0.027291     4.000000  
50%       2.333333     0.256410    13.000000  
75%       3.375000     0.448980    28.000000  
max      22.083333     1.000000   166.000000

In [ ]:
## 모범답안

x.describe()

<br/>

---

<br/>
<br/>

# 3. 데이터 전처리
* 전처리 과정을 통해서 머신러닝에 사용할 수 있는 형태의 데이터 준비


필요한 라이브러리를 불러옵니다.
- 인코딩 : LabelEncoder
- 데이터 표준화 : StandardScaler

In [8]:
# 사용할 알고리즘과 평가를 위한 함수 import 하기!
# 여기에 코드를 작성하세요
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [ ]:
## 모범답안

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler


* 단순히 1부터의 숫자를 부여한 'cust_id'를 수치형 변수로 받아들이면, 결과가 왜곡될 수 있으니 컬럼을 제거합니다.

In [9]:
# 여기에 코드를 작성하세요

# nparray 가 아니라 pandas dataframe이기 때문에 iloc로 슬라이싱
'''
x = x[:, 1:]
# y = yp:, -1]
'''
print(f"x : {type(x)} / y : {type(y)}")


x = x.iloc[:, 1:]
y = y.iloc[:, 1]

print(f"Shape\nx : {x.shape} / y : {y.shape}")

x : <class 'pandas.core.frame.DataFrame'> / y : <class 'pandas.core.frame.DataFrame'>
Shape
x : (3500, 9) / y : (3500,)


In [ ]:
## 모범답안

x = x.iloc[:, 1:]
y = y.iloc[:, -1]

- 데이터에 결측치가 있는지 확인해보세요


In [10]:
# 여기에 코드를 작성하세요
display(x.isnull().sum())
display(y.isnull().sum())

총구매액          0
최대구매액         0
환불금액       2295
주구매상품         0
주구매지점         0
내점일수          0
내점당구매건수       0
주말방문비율        0
구매주기          0
dtype: int64

np.int64(0)

In [ ]:
## 모범답안

x.isnull().sum()

- 결측치에 0으로 채워 넣어 모델 학습에 지장이 없도록 합니다.

In [11]:
# 여기에 코드를 작성하세요
x['환불금액'].fillna(0, inplace=True)

In [ ]:
## 모범답안

x['환불금액'].fillna(0, inplace=True)


문자형 범주 데이터를 숫자로 바꾸기 위한 인코딩을 수행합니다.

In [12]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   총구매액     3500 non-null   int64  
 1   최대구매액    3500 non-null   int64  
 2   환불금액     3500 non-null   float64
 3   주구매상품    3500 non-null   object 
 4   주구매지점    3500 non-null   object 
 5   내점일수     3500 non-null   int64  
 6   내점당구매건수  3500 non-null   float64
 7   주말방문비율   3500 non-null   float64
 8   구매주기     3500 non-null   int64  
dtypes: float64(3), int64(4), object(2)
memory usage: 246.2+ KB


In [13]:
# 문자형 변수를 숫자형 변수로 변환하기 위해 LabelEncoder를 사용 (LabelEncoder는 문자형 변수들을 0부터 차례대로 숫자를 부여함)
# 여기에 코드를 작성하세요

encoder = LabelEncoder()
obj_list = ['주구매상품', '주구매지점']

for col in obj_list:
    x[col] = encoder.fit_transform(x[col])

display(x.head())

총구매액     최대구매액       환불금액  주구매상품  주구매지점  내점일수   내점당구매건수    주말방문비율  구매주기
0  68282840  11264000  6860000.0      5      0    19  3.894737  0.527027    17
1   2136000   2136000   300000.0     21     19     2  1.500000  0.000000     1
2   3197000   1639000        0.0      6      1     2  2.000000  0.000000     1
3  16077620   4935000        0.0      5      2    18  2.444444  0.318182    16
4  29050000  24000000        0.0     15      8     2  1.500000  0.000000    85

In [ ]:
## 모범답안

from sklearn.preprocessing import LabelEncoder

col_lst = ['주구매상품', '주구매지점']

for col in col_lst:
	encoder = LabelEncoder()
	x[col] = encoder.fit_transform(x[col])

x.head()

In [14]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   총구매액     3500 non-null   int64  
 1   최대구매액    3500 non-null   int64  
 2   환불금액     3500 non-null   float64
 3   주구매상품    3500 non-null   int64  
 4   주구매지점    3500 non-null   int64  
 5   내점일수     3500 non-null   int64  
 6   내점당구매건수  3500 non-null   float64
 7   주말방문비율   3500 non-null   float64
 8   구매주기     3500 non-null   int64  
dtypes: float64(3), int64(6)
memory usage: 246.2 KB


# 4. 학습/테스트 데이터 분리


데이터를 학습용과 테스트용으로 나눕니다. (비율은 자유롭게 선택하세요)

In [15]:
# 여기에 코드를 작성하세요
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=777)

print(f"Shape : {x_train.shape}, {y_train.shape}, {x_test.shape}, {y_test.shape}")

Shape : (2800, 9), (2800,), (700, 9), (700,)


In [ ]:
## 모범답안
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                    test_size=0.20, random_state=11)

각 데이터에 표준화를 적용하여 데이터의 스케일(크기 차이)을 맞춰줍니다.
- 평균을 0, 표준편차를 1로 맞춰서 → 데이터가 정규 분포 형태로 변환되도록 하세요

In [16]:
x.columns

Index(['총구매액', '최대구매액', '환불금액', '주구매상품', '주구매지점', '내점일수', '내점당구매건수', '주말방문비율',
       '구매주기'],
      dtype='object')

In [18]:
# 여기에 코드를 작성하세요
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# 1

# x_train = scaler.fit_tranform(x_train)
# x_test = scaler.transform(x_test)


# 2

col_lst = ['총구매액', '최대구매액', '환불금액', '내점일수', '내점당구매건수', '주말방문비율', '구매주기']


x_train[col_lst] = scaler.fit_transform(x_train[col_lst])
x_test[col_lst] = scaler.transform(x_test[col_lst])

In [ ]:

## 모범답안


cols = ['총구매액', '최대구매액', '환불금액', '내점일수', '내점당구매건수', '주말방문비율', '구매주기']
scaler = StandardScaler()
scaler.fit(x_train[cols])
x_train[cols] = scaler.transform(x_train[cols])
x_test[cols] = scaler.transform(x_test[cols])

x_train.head()

<br/>

---

<br/>
<br/>

# 5-1. 모델링 - LogisticRegression

* 본격적으로 모델을 선언하고 학습시킵니다.

필요한 라이브러리를 불러오세요.

In [19]:
# 여기에 코드를 작성하세요
from sklearn.linear_model import LogisticRegression

모델을 선언하여 객체화시켜주세요.

In [21]:
# 여기에 코드를 작성하세요
model = LogisticRegression()


모델을 학습 데이터에 맞춰 학습시켜주세요.

In [22]:
# 여기에 코드를 작성하세요

model.fit(x_train, y_train)

LogisticRegression()

In [ ]:
## 모범 답안


# 1. 불러오기
from sklearn.linear_model import LogisticRegression

# 2. 선언하기
model = LogisticRegression()

# 3. 학습하기
model.fit(x_train, y_train)

<br/>

---

<br/>
<br/>

# 6-1. 예측 성능 확인해보기 - LogisticRegression

- 학습된 모델로 테스트 데이터에 대한 예측을 수행합니다.

In [24]:
# 여기에 코드를 작성하세요

pred = model.predict(x_test)


- 학습시킨 모델의 성능을 알아봅니다.
- 각 평가지표로 모델의 성능을 수치화하여 확인합니다.
- 필요한 라이브러리를 import 하고 성능을 확인해보세요 (정확도, 정밀도, 재현율, f1, confusion_matrix)

In [27]:
# 여기에 코드를 작성하세요
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score

confusion = confusion_matrix(y_test,pred)

acc = accuracy_score(y_test,pred)
recall = recall_score(y_test,pred)
prec = precision_score(y_test,pred)
f1 = f1_score(y_test,pred)

print(f"{confusion} \n {acc} \n {recall} \n {prec} \n {f1}")

[[412  21]
 [243  24]] 
 0.6228571428571429 
 0.0898876404494382 
 0.5333333333333333 
 0.15384615384615385


In [ ]:
## 모범답안




# 테스트 데이터 예측하기
pred = model.predict(x_test)

## 평가지표 확인

from sklearn.metrics import accuracy_score, precision_score , recall_score, f1_score
from sklearn.metrics import confusion_matrix

confusion = confusion_matrix(y_test, pred)
accuracy = accuracy_score(y_test , pred)
precision = precision_score(y_test , pred)
recall = recall_score(y_test , pred)
f1 = f1_score(y_test,pred)

print('오차 행렬')
print(confusion)

print(f'정확도: {accuracy}, 정밀도: {precision}, 재현율: {recall}, F1: {f1}')



<br/>

---

<br/>
<br/>

# 5-2. 모델링 - DecisionTreeClassifier

* 본격적으로 모델을 선언하고 학습시킵니다.


필요한 라이브러리를 불러오세요.

In [47]:
# 여기에 코드를 작성하세요
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [ ]:
## 모범답안

# 불러오기
from sklearn.tree import DecisionTreeClassifier

모델을 선언하여 객체화시킵니다.

In [32]:
# 여기에 코드를 작성하세요
model = DecisionTreeClassifier()

In [ ]:
## 모범답안

# 선언하기
model = DecisionTreeClassifier(max_depth=10)

모델을 학습 데이터에 맞춰 학습시킵니다.

In [33]:
# 여기에 코드를 작성하세요
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
## 모범답안

# 학습하기
model.fit(x_train, y_train)



<br/>
<br/>

# 6-2. 예측 성능 확인해보기 - DecisionTreeClassifier

- 학습된 모델로 테스트 데이터에 대한 예측을 수행합니다.

In [34]:
# 여기에 코드를 작성하세요
pred = model.predict(x_test)


In [ ]:
## 모범답안

# 테스트 데이터 예측하기
pred = model.predict(x_test)

- 학습시킨 모델의 성능을 알아봅니다
- 각 평가지표로 모델의 성능을 수치화하여 확인합니다.
- 필요한 라이브러리를 import 하고 성능을 확인해보세요 (정확도, 정밀도, 재현율, f1, confusion_matrix)

In [35]:
# 여기에 코드를 작성하세요
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

confusion = confusion_matrix(y_test,pred)
accuracy = accuracy_score(y_test,pred)
precision = precision_score(y_test,pred)
recall = recall_score(y_test,pred)
f1 = f1_score(y_test,pred)

print(f"{confusion} \n {acc} \n {recall} \n {prec} \n {f1}")

[[284 149]
 [172  95]] 
 0.6228571428571429 
 0.35580524344569286 
 0.5333333333333333 
 0.37181996086105673


In [ ]:

## 모범답안

# 평가지표 확인

from sklearn.metrics import accuracy_score, precision_score , recall_score, f1_score
from sklearn.metrics import confusion_matrix

confusion = confusion_matrix(y_test, pred)
accuracy = accuracy_score(y_test , pred)
precision = precision_score(y_test , pred)
recall = recall_score(y_test , pred)
f1 = f1_score(y_test,pred)

print('오차 행렬')
print(confusion)

print(f'정확도: {accuracy}, 정밀도: {precision}, 재현율: {recall}, F1: {f1}')



<br/>

---

<br/>
<br/>

# 5-3. 모델링 - RandomForestClassifier

* 본격적으로 모델을 선언하고 학습시킵니다.



필요한 라이브러리를 불러옵니다.

In [36]:
# 여기에 코드를 작성하세요
from sklearn.ensemble import RandomForestClassifier

In [ ]:
##모범답안

# 불러오기
from sklearn.ensemble import RandomForestClassifier

모델을 선언하여 객체화시킵니다.

In [37]:
# 여기에 코드를 작성하세요
model = RandomForestClassifier()

In [ ]:
##모범답안

# 선언하기
model = RandomForestClassifier()

모델을 학습 데이터에 맞춰 학습시킵니다.

In [38]:
# 여기에 코드를 작성하세요
model.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
## 모범답안

# 학습하기
model.fit(x_train, y_train)



<br/>
<br/>

# 6-3. 예측 성능 확인해보기 - RandomForestClassifier

- 학습된 모델로 테스트 데이터에 대한 예측을 수행합니다.

In [39]:
# 여기에 코드를 작성하세요

pred = model.predict(x_test)

In [ ]:
##모범답안

# 테스트 데이터 예측하기
pred = model.predict(x_test)

- 학습시킨 모델의 성능을 알아봅니다
- 각 평가지표로 모델의 성능을 수치화하여 확인합니다.
- 필요한 라이브러리를 import 하고 성능을 확인해보세요 (정확도, 정밀도, 재현율, f1, confusion_matrix)

In [40]:
# 여기에 코드를 작성하세요

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

confusion = confusion_matrix(y_test,pred)
accuracy = accuracy_score(y_test,pred)
precision = precision_score(y_test,pred)
recall = recall_score(y_test,pred)
f1 = f1_score(y_test,pred)

print(f"{confusion} \n {acc} \n {recall} \n {prec} \n {f1}")

[[356  77]
 [184  83]] 
 0.6228571428571429 
 0.31086142322097376 
 0.5333333333333333 
 0.38875878220140514


In [ ]:

## 모범답안

# 평가지표 확인

from sklearn.metrics import accuracy_score, precision_score , recall_score, f1_score
from sklearn.metrics import confusion_matrix

confusion = confusion_matrix(y_test, pred)
accuracy = accuracy_score(y_test , pred)
precision = precision_score(y_test , pred)
recall = recall_score(y_test , pred)
f1 = f1_score(y_test,pred)

print('오차 행렬')
print(confusion)

print(f'정확도: {accuracy}, 정밀도: {precision}, 재현율: {recall}, F1: {f1}')



<br/>

---

<br/>
<br/>

# 5-4. 모델링 - XGBoost

* 본격적으로 모델을 선언하고 학습시킵니다.



필요한 라이브러리를 불러오세요.

In [42]:
# 여기에 코드를 작성하세요
from xgboost import XGBClassifier

In [ ]:
## 모범답안

# 불러오기
from xgboost import XGBClassifier

모델을 선언하여 객체화시켜주세요.

In [43]:
# 여기에 코드를 작성하세요
model = XGBClassifier()

In [ ]:
# 선언하기
model = XGBClassifier(n_estimators=100, max_depth=3)

모델을 학습 데이터에 맞춰 학습시켜주세요.

In [44]:
# 여기에 코드를 작성하세요
model.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
## 모범답안

# 학습하기
model.fit(x_train, y_train)



<br/>
<br/>

# 6-4. 예측 성능 확인해보기 - XGBoost

- 학습된 모델로 테스트 데이터에 대한 예측을 수행합니다.

In [45]:
# 여기에 코드를 작성하세요
pred = model.predict(x_test)

In [ ]:
##모범답안

# 테스트 데이터 예측하기
pred = model.predict(x_test)

- 학습시킨 모델의 성능을 알아봅니다
- 각 평가지표로 모델의 성능을 수치화하여 확인합니다.
- 필요한 라이브러리를 import 하고 성능을 확인해보세요 (정확도, 정밀도, 재현율, f1, confusion_matrix)

In [46]:
# 여기에 코드를 작성하세요

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

confusion = confusion_matrix(y_test,pred)
accuracy = accuracy_score(y_test,pred)
precision = precision_score(y_test,pred)
recall = recall_score(y_test,pred)
f1 = f1_score(y_test,pred)

print(f"{confusion} \n {acc} \n {recall} \n {prec} \n {f1}")

[[334  99]
 [170  97]] 
 0.6228571428571429 
 0.36329588014981273 
 0.5333333333333333 
 0.4190064794816415


In [ ]:

## 모범답안

# 평가지표 확인

from sklearn.metrics import accuracy_score, precision_score , recall_score, f1_score
from sklearn.metrics import confusion_matrix

confusion = confusion_matrix(y_test, pred)
accuracy = accuracy_score(y_test , pred)
precision = precision_score(y_test , pred)
recall = recall_score(y_test , pred)
f1 = f1_score(y_test,pred)

print('오차 행렬')
print(confusion)

print(f'정확도: {accuracy}, 정밀도: {precision}, 재현율: {recall}, F1: {f1}')


<br/>

---


<br/>

## 7.  위 4가지 모델의 학습 & 예측 & 평가 결과를 확인하고 최고 성능을 내는 모델을 찾아봅시다!

- 어떤 모델이 가장 성능이 좋은가요 ?